### ISSUE TITLE
Where i can change default Description in new bug creation?

### ISSUE THREAD

**Issue by nesesser** [a-v-k/phpBugTracker#11]
I need to set some text in Description when Add new bug is pressed. Where i can find it?

**Comment by a-v-k** [comment]
Description field must be appear at "Add new bug" form. See screenshot bellow.
If you have no Description field - check permissions settings.

(https://cloud.githubusercontent.com/assets/1016615/17580966/41c225ca-5fab-11e6-8365-a5d07f5f9229.png)

**Comment by nesesser** [comment]
I'm sorry, i supposed that text have to be already writen as default value.

**Comment by nesesser** [comment]
I want to set default value:
---------
AS IS:
AS SUPPOSED TO BE:
COMMENTS:
---------

**Comment by a-v-k** [comment]
Sorry, there is no that feature yet.

**Comment by nesesser** [comment]
Yes, Im already found out that :) But please can you give me a clue where I can find proper php-file to change it by myself?

**Comment by a-v-k** [comment]
I see, default values for new bug set in bug.php, line about 858 https://github.com/a-v-k/phpBugTracker/blob/b6f33be4372e1a64a2a4ea60797a0dde55819dee/bug.php#L858 
You can add 'description' field to that place. 
But, I think, it must be customizable at project settings level

**Comment by nesesser** [comment]
Sure, it should be customizable. But its too complicated to implement immediately.
And thx for clue.
