### ISSUE TITLE
PHP 7.2.0 breaks admin

### ISSUE THREAD

**Issue by dominik96** [a-v-k/phpBugTracker#12]
PHP Fatal error: Uncaught ErrorException: The each() function is deprecated. This message will be suppressed on further calls in /usr/share/phpbugtracker/inc/functions.php:383\nStack trace:\n#0 [internal function]: exception_error_handler(8192, 'The each() func...', '/usr/share/phpb...', 383, Array)\n#1 /usr/share/phpbugtracker/inc/functions.php(383): each(Array)\n#2 /usr/share/phpbugtracker/admin/project.php(449): sorting_headers('/bugtracker/adm...', Array, 'default', 'asc')\n#3 /usr/share/phpbugtracker/admin/project.php(484): list_projects()\n#4 {main}\n thrown in /usr/share/phpbugtracker/inc/functions.php on line 383, referer: http://localhost/bugtracker/index.php

**Comment by a-v-k** [comment]
Thank you for report! I will fix it soon.

**Comment by a-v-k** [comment]
Hello! Try this version: https://github.com/a-v-k/phpBugTracker/archive/5c075edff33262a3ebc6ff9b65e759b978c1b1fd.zip

It must be ok.

**Comment by a-v-k** [comment]
fixed in 1.7.9

**Comment by dominik96** [comment]
yes it works now! Thank you
