### ISSUE TITLE
v1.7.1/v1.7.2 Add Bug error

### ISSUE THREAD

**Issue by bLightZP** [a-v-k/phpBugTracker#5]
After upgrading from v1.7.0 to 1.7.1 or 1.7.2, clicking on the Add Bug url shows "Invalid parameter value for: project".

Going back to 1.7.0 and it works again.

**Comment by a-v-k** [comment]
Hello!
Thank you for report.
I just rechecked "add bug" process and I can't find any problem.
Please, provide additional information:
- send me a screenshot of browser, captured in moment, when the mouse pointed to broken link and before click. 
- send me a source of page with link.

**Comment by a-v-k** [comment]
Are you trying to add bug via authenticated or non-authenticated user?

**Comment by bLightZP** [comment]
The bug is added via authenticated user, it's done by clicking the 'Add a new bug' link at the top of the page (under the phpBugTracker logo).

The browser is the latest version of FireFox with "Adblock Plus" and "Disconnect" addons enabled.

I can send you a link to the website by mail if you share it, I don't want to expose the site's URL in a public forum.

**Comment by a-v-k** [comment]
Send your message to temp-001@digicraft.ru . I will response from my personal address.

**Comment by a-v-k** [comment]
Probably, I found and fix this bug. But I can't test it.
Current master version (https://github.com/a-v-k/phpBugTracker/archive/master.zip) must help you.
Please, update your instance to master version and write here about results.

**Comment by a-v-k** [comment]
Fixed at 1.7.4
