### ISSUE TITLE
Can't add new bug

### ISSUE THREAD

**Issue by burtamus2003** [a-v-k/phpBugTracker#6]
I just downloaded and installed phpBT. I had to delete and recreate my DB and user a few times before I got the correct config.php. I added a few of my programmers and QA team.  Now, when I go to add a new bug at my site, it does not have any submit button as in the documentation. I have tried Firefox and Chrome.

**Comment by a-v-k** [comment]
Do you added any projects before add bug to it?
Please send me screenshot of "add bug" page.

**Comment by burtamus2003** [comment]
Sure did.
![addbug](https://cloud.githubusercontent.com/assets/11802040/6999471/eac4df00-dbd1-11e4-9479-b3fd344102a9.png)

**Comment by a-v-k** [comment]
Ok. I probably found the problem. It's about 'upload_max_filesize' ini setting or ATTACHMENT_MAX_SIZE config setting.
I will fix it soon. 
Please, try current development version. It must help you. And please write here about result.
Download: https://github.com/a-v-k/phpBugTracker/archive/dev.zip

**Comment by a-v-k** [comment]
Fixed at version 1.7.5
